#!/usr/bin/env bash
# Deploy the PXE boot-chain compatibility fix for older Dell/HP IPv4 PXE ROMs.
#
# Run this on the FOG/imaging server after extracting the updated bundle:
#   sudo bash tools/deploy_pxe_legacy_bootfix.sh
#
# It intentionally touches only:
#   - dnsmasq ProxyDHCP config
#   - PXE publish script and generated /var/www/html/vstl-pxe boot assets
#   - /tftpboot/vstl.ipxe and /tftpboot/autoexec.ipxe generated by step 06
set -euo pipefail

die() { echo "FATAL: $*" >&2; exit 1; }
log() { echo "[$(date +%H:%M:%S)] $*"; }

[[ $EUID -eq 0 ]] || die "Run as root (use sudo)."

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
SRC_ROOT="$(cd "$SCRIPT_DIR/.." >/dev/null 2>&1 && pwd)"

INSTALL_ROOT="${INSTALL_ROOT:-}"
if [[ -z "$INSTALL_ROOT" ]]; then
    for candidate in /opt/vstl-imaging-phase1 /opt/vstl-imaging; do
        if [[ -f "$candidate/build/vstl-live-amd64.iso" ]]; then
            INSTALL_ROOT="$candidate"
            break
        fi
    done
fi

[[ -n "$INSTALL_ROOT" ]] || die "Could not find install root. Set INSTALL_ROOT=/opt/vstl-imaging or /opt/vstl-imaging-phase1."
[[ -d "$INSTALL_ROOT" ]] || die "Install root does not exist: $INSTALL_ROOT"
[[ -f "$INSTALL_ROOT/build/vstl-live-amd64.iso" ]] || die "Missing ISO at $INSTALL_ROOT/build/vstl-live-amd64.iso"

PXE_ROOT="${PXE_ROOT:-/var/www/html/vstl-pxe}"
TFTP_ROOT="${TFTP_ROOT:-/tftpboot}"
BACKUP_ROOT="${BACKUP_ROOT:-/opt/vstl-backups}"
TS="$(date +%Y%m%d_%H%M%S)"
BACKUP_DIR="$BACKUP_ROOT/pxe-legacy-bootfix-$TS"

for f in 02_install_dnsmasq.sh 03_dnsmasq_proxydhcp.conf 06_setup_pxe_netboot.sh; do
    [[ -f "$SRC_ROOT/$f" ]] || die "Bundle is missing $f"
done

log "Backing up current PXE/DNSMASQ state to $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"
[[ -f /etc/dnsmasq.d/vstl-imaging.conf ]] && cp -a /etc/dnsmasq.d/vstl-imaging.conf "$BACKUP_DIR/vstl-imaging.conf.bak"
[[ -d "$PXE_ROOT" ]] && tar -czf "$BACKUP_DIR/vstl-pxe-before.tar.gz" -C "$(dirname "$PXE_ROOT")" "$(basename "$PXE_ROOT")"
for f in vstl.ipxe autoexec.ipxe; do
    [[ -f "$TFTP_ROOT/$f" ]] && cp -a "$TFTP_ROOT/$f" "$BACKUP_DIR/$f.bak"
done

log "Installing updated PXE fix scripts into $INSTALL_ROOT"
install -m 0755 "$SRC_ROOT/02_install_dnsmasq.sh" "$INSTALL_ROOT/02_install_dnsmasq.sh"
install -m 0755 "$SRC_ROOT/06_setup_pxe_netboot.sh" "$INSTALL_ROOT/06_setup_pxe_netboot.sh"
install -m 0644 "$SRC_ROOT/03_dnsmasq_proxydhcp.conf" "$INSTALL_ROOT/03_dnsmasq_proxydhcp.conf"

log "Reinstalling dnsmasq ProxyDHCP config for legacy PXE compatibility"
(cd "$INSTALL_ROOT" && ./02_install_dnsmasq.sh)

log "Regenerating PXE HTTP/TFTP boot assets with named initrd handoff"
(cd "$INSTALL_ROOT" && ./06_setup_pxe_netboot.sh)

cat <<EOF

PXE LEGACY BOOT FIX DEPLOYED

Install root : $INSTALL_ROOT
Backup dir   : $BACKUP_DIR
PXE root     : $PXE_ROOT
TFTP root    : $TFTP_ROOT

Now test one affected laptop:
  - Dell Latitude 5490 / 5470: F12 -> PXE IPv4
  - HP ProBook 640 G1/G2: F9 or F12 -> PXE IPv4

Watch live:
  sudo journalctl -u dnsmasq -f
  sudo tail -f /var/log/apache2/access.log

EOF
